linters:
  LineLength:
    enabled: false
  AccessibleAlt:
    enabled: true
  NoEmptyElements:
    enabled: false
  ExcludedFiles:
    'app/views/layouts/application.html.slim':
      lines: [18]

include_linters:
  - Linter::LineLength
  - Linter::AccessibleAlt
  - Linter::NoEmptyElements